name: Release

on:
  push:
    tags:
    - 'v*'

env:
  PROJECT_PATH: ~

jobs:
  build:
    runs-on: ubuntu-20.04

    env:
      MGFXC_WINE_PATH: /home/runner/.winemonogame

    steps:
    - uses: actions/checkout@v2
    - name: Setup dotnet
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '7.0.x'
    - name: Get version from tag
      run: |
        TAGVERSION=$(git describe --tags --abbrev=0)
        echo "TAGVERSION=${TAGVERSION:1}" >> $GITHUB_ENV
    - name: Setup Wine
      run: |
        sudo apt update
        sudo apt install wine64 p7zip-full
        wget -qO- https://raw.githubusercontent.com/MonoGame/MonoGame/master/Tools/MonoGame.Effect.Compiler/mgfxc_wine_setup.sh | sh
    - name: Build Windows
      run: dotnet publish ${{ env.PROJECT_PATH }} -r win-x64 -c Release --self-contained --output artifacts/windows
    - name: Build Osx
      run: dotnet publish ${{ env.PROJECT_PATH }} -r osx-x64 -c Release --self-contained --output artifacts/osx
    - name: Build Linux
      run: dotnet publish ${{ env.PROJECT_PATH }} -r linux-x64 -c Release --self-contained --output artifacts/linux
    - name: Zip
      run: |
        zip -r artifacts/windows.zip artifacts/windows
        zip -r artifacts/osx.zip artifacts/osx
        zip -r artifacts/linux.zip artifacts/linux
    - name: Release with Notes
      uses: softprops/action-gh-release@v1
      with:
        files: |
          artifacts/windows.zip
          artifacts/osx.zip
          artifacts/linux.zip
